Back top the working situation

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -40,35 +40,34 @@ runs:
       id: sanity-check
       shell: bash
       run: |
+        export $(echo "${{ inputs.sanity-secrets }}" | xargs)
         rm -rf ${{ inputs.results-path }}
         mkdir ${{ inputs.results-path }}
         chmod 777 ${{ inputs.results-path }}
-        export FAILED=1
-        export $(echo "${{ inputs.sanity-secrets }}" | xargs)
-        # docker container run -v "${{ inputs.results-path }}":"/home/testing/reports" --rm \
-        #   -ereports inputs.api-base-url }}" \
-        #   -e APP_BASE_URL="${{ inputs.app-base-url }}" \
-        #   -e ADMIN_BASE_URL="${{ inputs.admin-base-url }}" \
-        #   -e SELENIUM_USERNAME=${SELENIUM_USERNAME} \
-        #   -e SELENIUM_USER_PASSWORD=${SELENIUM_USER_PASSWORD} \
-        #   -e PROTON_MAIL=${PROTON_MAIL} \
-        #   -e PROTON_MAIL_PASSWORD=${PROTON_MAIL_PASSWORD} \
-        #   -e API_USER=${API_USER} \
-        #   -e API_USER_PASSWORD=${API_USER_PASSWORD} \
-        #   -e API_ADMIN_USER=${API_ADMIN_USER} \
-        #   -e API_ADMIN_PASSWORD=${API_ADMIN_PASSWORD} \
-        #   -e G_ADMIN_PASSWORD=${G_ADMIN_PASSWORD} \
-        #   -e G_USER_PASSWORD=${G_USER_PASSWORD} \
-        #   ${{ inputs.selenium-image }} || FAILED=1
+        export FAILED=0
+        docker container run -v "${{ inputs.results-path }}":"/home/testing/reports" --rm \
+          -ereports inputs.api-base-url }}" \
+          -e APP_BASE_URL="${{ inputs.app-base-url }}" \
+          -e ADMIN_BASE_URL="${{ inputs.admin-base-url }}" \
+          -e SELENIUM_USERNAME=${SELENIUM_USERNAME} \
+          -e SELENIUM_USER_PASSWORD=${SELENIUM_USER_PASSWORD} \
+          -e PROTON_MAIL=${PROTON_MAIL} \
+          -e PROTON_MAIL_PASSWORD=${PROTON_MAIL_PASSWORD} \
+          -e API_USER=${API_USER} \
+          -e API_USER_PASSWORD=${API_USER_PASSWORD} \
+          -e API_ADMIN_USER=${API_ADMIN_USER} \
+          -e API_ADMIN_PASSWORD=${API_ADMIN_PASSWORD} \
+          -e G_ADMIN_PASSWORD=${G_ADMIN_PASSWORD} \
+          -e G_USER_PASSWORD=${G_USER_PASSWORD} \
+          ${{ inputs.selenium-image }} || FAILED=1
         echo "::set-output name=sanity-failed::$FAILED"
 
     - name: Break if failed
       shell: bash
       run: |
-        echo HELLO: ${{ inputs.continue-if-failed }}
+        test ${{ steps.sanity-check.outputs.sanity-failed }} -eq 0 || echo "Tests failed. Please check the results on ${{ inputs.results-path }}"
         if [ ${{ inputs.continue-if-failed }} == false ]
         then
-          echo BYE ${{ steps.sanity-check.outputs.sanity-failed }}
           test ${{ steps.sanity-check.outputs.sanity-failed }} -eq 0
         fi
-        echo BYE BYE BYE
+        echo "All tests successfully passed. The resutls are available on ${{ inputs.results-path }}"
